version: 0.0
os: linux
files:
  - source: .
    destination: /artemis
hooks:
  BeforeInstall:
    - location: cicd-test-master/scripts/prepare.sh
      timeout: 3600
      runas: ec2-user
  ApplicationStart:
    - location: cicd-test-master/scripts/start_application.sh
      timeout: 3600
      runas: ec2-user
  ApplicationStop:
    - location: cicd-test-master/scripts/stop_application.sh
      timeout: 3600
      runas: ec2-user
