version: '3.5'
services:

  data:
    build:
      context: .
      dockerfile: './data/Dockerfile'
    container_name: 'production-testdata-service'
    volumes:
      - ~/.aws:/root/.aws


  analytics:
    build:
      context: .
      dockerfile: './analytics/Dockerfile'
    container_name: 'production-analytic-service'
#    environment:
#      - PYTHONUNBUFFERED=0
    command:
      - /bin/sh
      - -c
      - |
          cd analytics
          gunicorn --workers 2 --timeout 500 --graceful-timeout 480 --bind=0.0.0.0:9001 hug_serve:__hug_wsgi__
    ports:
      - "9001:9001"
    expose:
      - "9001"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ~/.aws:/root/.aws
      - ./analytics:/app/analytics